# Generated by Django 2.1.7 on 2019-04-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='students',
            name='year',
        ),
    ]
