# Generated by Django 2.1.7 on 2019-04-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20190407_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Branch',
            field=models.CharField(choices=[('INFT', 'INFT'), ('COMPS', 'COMPS'), ('CIVIL', 'CIVIL'), ('MECH', 'MECH'), ('INST', 'INST')], default='aa', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='year',
            field=models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='aa', max_length=10),
        ),
    ]
