# Generated by Django 2.1.7 on 2019-04-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20190407_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='clgId',
            new_name='ClgId',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='Event_Name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='student_name',
            new_name='Student_Name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='year',
            new_name='Year',
        ),
        migrations.AddField(
            model_name='students',
            name='Attended',
            field=models.BooleanField(default=False),
        ),
    ]
