# Generated by Django 2.1.7 on 2019-04-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_auto_20190408_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='ClgId',
            new_name='clgId',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Event_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Student_Name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Attended',
        ),
    ]
