# Generated by Django 2.1.7 on 2019-04-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_auto_20190411_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='clgId',
            field=models.CharField(max_length=10),
        ),
    ]
