# Generated by Django 2.1.7 on 2019-04-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_event_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='total_seats',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
