# Generated by Django 2.1.7 on 2019-04-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
